title: Marcos Júnio Ribeiro
description: My website

url: https://mj-ribeiro.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Início
    url: /index.html
  - title: Sobre
    url: /about
  - title: Pesquisa
    url: /pesquisa
  - title: Ensino
    url: /ensino
 

social:
  github: mj-ribeiro
  linkedin: marcos-ribeiro-economics-analysis
  email: mjribeiro@usp.br

google_analytics: "UA-58263416-1"
